### ISSUE TITLE
do we really need pg-native? 

### ISSUE THREAD

**Issue by Oele** [Richie765/meteor-pg#1]
Is there any specific reason why pg-native is listed as a dependency in package.json? 

As far as i can see, it's not used by meteor-pg itself and it's optional in all other dependencies. 

This dependency is keeping meteor-pg from working on Meteor Galaxy, since the native pg libs are not available there. 

After removing the dependency, it seems to be working fine.

**Comment by Richie765** [comment]
Looks like you're right. Must have been a left-over from before. I remove it and published a new version. Tnx.

**Comment by ethanwillis** [comment]
I ran into this issue as well. It looks like version 1.0.7 that removes pg-native wasn't pushed to NPM.. NPM still pulls in 1.0.6 with the pg-native dependency

**Comment by Richie765** [comment]
I published to my own private registry lol. It should be published correctly now, let me know if you still have any issues!
