### ISSUE TITLE
DONATION

### ISSUE THREAD

**Issue by adammoisa** [Richie765/meteor-pg#4]
You rock. This package opens many doors for me. If you accept donations as thanks I’d like to be able to say thank you - but I don’t see any link to such a thing. Obv feel free to close this issue quickly as it’s not an issue and email me directly - adam@moisaconsulting.com. Either way, thank you so much.

**Comment by Richie765** [comment]
Thanks Adam for your comment! It's good to hear it is so useful for you! Really appreciate your gesture but it's not necessary to donate anything. It was a fun project and I learned quite a bit from it. In part it is based on the work of other's as well. Thanks again!
